stages:
  - build

build:
  stage: build
  image: docker:18.09
  services:
    - docker:18.09-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
  script:
    - docker build . -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
