stages:
  - build

variables:
  DOCKER_HOST: tcp://docker:2375
  APP_IMAGE: ${CI_PROJECT_PATH}
  APP_DEV_IMAGE: ${CI_PROJECT_PATH}/dev
  APP_BASE_IMAGE: ${CI_PROJECT_PATH}/base
  REVERSE_PROXY_IMAGE: ${CI_PROJECT_PATH}/fcgi-proxy

build:
  stage: build
  image: docker:18.09
  services:
    - docker:18.09-dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - apk add --no-cache parallel
  script:
    - docker build . -t $APP_BASE_IMAGE:$CI_COMMIT_REF_SLUG --target base
    - docker build . -t $APP_DEV_IMAGE:$CI_COMMIT_REF_SLUG --target dev --cache-from $APP_BASE_IMAGE:$CI_COMMIT_REF_SLUG
    - docker build . -t $APP_IMAGE:$CI_COMMIT_REF_SLUG --cache-from $APP_DEV_IMAGE:$CI_COMMIT_REF_SLUG
    - docker build infra/nginx -t $REVERSE_PROXY_IMAGE:$CI_COMMIT_REF_SLUG
    - "parallel docker push ::: \
        ${CI_REGISTRY}/${APP_IMAGE}:${CI_COMMIT_REF_SLUG} \
        ${CI_REGISTRY}/${APP_DEV_IMAGE}:${CI_COMMIT_REF_SLUG} \
        ${CI_REGISTRY}/${APP_BASE_IMAGE}:${CI_COMMIT_REF_SLUG} \
        ${CI_REGISTRY}/${REVERSE_PROXY_IMAGE}:${CI_COMMIT_REF_SLUG} \
      "
